#' Plot the Inferred Bayesian Boolean Network
#'
#' @description
#' Visualizes the causal network structure inferred by the BBNI MCMC sampler.
#' This function takes the marginal posterior probability of each directed edge
#' and plots the network using the \code{igraph} package. Edges with posterior
#' probabilities below the specified threshold are omitted from the plot.
#'
#' @param results The list returned by \code{run_bbni()}, containing \code{networks} and \code{log_posterior}.
#' @param threshold Numeric. The minimum posterior probability required to draw an edge. Defaults to 0.5.
#' @param node_names Character vector. Optional names for the nodes. Defaults to "N1", "N2", etc.
#' @param ... Additional graphical parameters passed to \code{igraph::plot.igraph()}.
#'
#' @return An invisible \code{igraph} object.
#'
#' @examples
#' \donttest{
#' # 1. Generate synthetic network and time-series data
#' set.seed(123)
#' true_network <- GenerateNetwork(num.node = 5)
#' dummy_data <- GenerateSample(true_network, SampleSize = 15)
#'
#' # 2. Run BBNI sampler
#' prior_para <- matrix(3, nrow = 6, ncol = 2)
#' prior_para[6, 1] <- 2
#' prior_para[6, 2] <- 100
#'
#' results <- run_bbni(dummy_data, prior_para = prior_para, num_update = 100)
#'
#' # 3. Plot inferred network
#' plot_bbni(results, threshold = 0.5)
#' }
#'
#' @importFrom igraph graph_from_adjacency_matrix plot.igraph
#' @export
plot_bbni <- function(results, threshold = 0.5, node_names = NULL, ...) {
  # Make sure igraph is available
  if (!requireNamespace("igraph", quietly = TRUE)) {
    stop("Package \"igraph\" is required for plotting. Please install it.", call. = FALSE)
  }
  # Extract list of networks and calculate posterior probabilities (res)
  if (!is.null(results$post_edge_prob)) {
    res <- results$post_edge_prob
  } else {
    # fallback by manually calculate
    networks <- results$networks
    res <- Reduce(`+`, lapply(networks, function(m) (m > 0) * 1)) / length(networks)
  }
  # Filter probability matrix based on threshold
  adj_matrix <- ifelse(res >= threshold, 1, 0)
  # Assign node names if provided, otherwise default to N1, N2...
  num_nodes <- nrow(res)
  if (is.null(node_names)) {
    colnames(adj_matrix) <- rownames(adj_matrix) <- paste0("N", 1:num_nodes)
  } else {
    colnames(adj_matrix) <- rownames(adj_matrix) <- node_names
  }
  # Create directed graph
  g <- igraph::graph_from_adjacency_matrix(t(adj_matrix), mode = "directed")
  # Plot with defaults
  igraph::plot.igraph(g,
                      vertex.size = 20,
                      vertex.color = "lightblue",
                      vertex.label.color = "black",
                      vertex.label.cex = 0.8,
                      edge.arrow.size = 0.5,
                      edge.color = "darkgray",
                      main = paste("Inferred Network (Threshold >", threshold, ")"),
                      ...)
  # Return graph object invisibly in case user wants to manipulate it further
  invisible(g)
}

#' Plot a Single Boolean Network
#'
#' Visualizes a single directed network topology. For instance, a synthetic "true" network
#' generated by \code{GenerateNetwork()}.
#'
#' @param trans_matrix A square matrix representing the network topology and Boolean rules (e.g., the output of \code{GenerateNetwork()}). Elements greater than 0 indicate a directed edge.
#' @param node_names Character vector. Optional names for the nodes. Defaults to "N1", "N2", etc.
#' @param ... Additional graphical parameters passed to \code{igraph::plot.igraph()}.
#'
#' @return An invisible \code{igraph} object.
#'
#' @examples
#' \donttest{
#' # 1. Generate synthetic 5-node network topology
#' set.seed(123)
#' true_network <- GenerateNetwork(num.node = 5)
#'
#' # 2. Plot the generated network
#' plot_network(true_network)
#' }
#'
#' @importFrom igraph graph_from_adjacency_matrix plot.igraph
#' @export
plot_network <- function(trans_matrix, node_names = NULL, ...) {
  # Make sure igraph is available
  if (!requireNamespace("igraph", quietly = TRUE)) {
    stop("Package \"igraph\" is required for plotting. Please install it.", call. = FALSE)
  }
  adj_matrix <- (trans_matrix > 0) * 1
  num_nodes <- nrow(adj_matrix)
  if (is.null(node_names)) {
    colnames(adj_matrix) <- rownames(adj_matrix) <- paste0("N", 1:num_nodes)
  } else {
    colnames(adj_matrix) <- rownames(adj_matrix) <- node_names
  }
  g <- igraph::graph_from_adjacency_matrix(t(adj_matrix), mode = "directed")
  igraph::plot.igraph(g, vertex.size = 20, vertex.color = "lightblue",
                      vertex.label.color = "black", vertex.label.cex = 0.8,
                      edge.arrow.size = 0.5, edge.color = "darkgray",
                      main = "Network Topology", ...)
  invisible(g)
}

#' Plot MCMC Trace for BBNI
#'
#' @description
#' Generates a trace plot of the log-posterior values over iterations of the MCMC
#' to visually assess convergence and stability of the executed Markov chain.
#' Burn-in line is graphed to show when the data started to be utilized for
#' edge-probability calculations.
#'
#' @param results The list returned by \code{run_bbni()}, containing \code{networks} and \code{log_posterior}.
#'
#' @return A base R trace plot.
#'
#' @examples
#' \donttest{
#' # 1. Generate synthetic network and time-series data
#' set.seed(123)
#' true_network <- GenerateNetwork(num.node = 5)
#' dummy_data <- GenerateSample(true_network, SampleSize = 15)
#'
#' # 2. Run BBNI sampler
#' prior_para <- matrix(3, nrow = 6, ncol = 2)
#' prior_para[6, 1] <- 2
#' prior_para[6, 2] <- 100
#'
#' results <- run_bbni(dummy_data, prior_para = prior_para, num_update = 100)
#'
#' # 3. Visualize MCMC results
#' plot_trace(results)
#' }
#'
#' @importFrom graphics plot abline legend
#' @export
plot_trace <- function(results) {
  logpost <- results$log_posterior
  plot(logpost, type = "l", col = "darkblue",
       xlab = "Iteration", ylab = "Log-Posterior",
       main = "MCMC Trace Plot",
       lwd = 1.5)
  # add vertical line for burn-in if present
  if (!is.null(results$burn_in)) {
    abline(v = results$burn_in * length(results$log_posterior), col = "red", lty = 2)
    legend("bottomright", legend = paste("Burn-in =", results$burn_in), col = "red", lty = 2, bty = "n")
  }
}
